# -*- coding: utf-8 -*-
"""
Created on Sat Feb 27 13:01:13 2021

@author: kneub
"""

# List of skills from html export
skill_list = ['Overall','Attack','Defence','Strength','Hitpoints','Ranged','Prayer','Magic','Cooking',
              'Woodcutting','Fletching','Fishing','Firemaking','Crafting','Smithing',
              'Mining','Herblore','Agility','Thieving','Slayer','Farming','Runecraft',
              'Hunter','Construction']

# List of bosses from html export
pvm_list = ['Bounty Hunter - Hunter','Clue Scrolls (all)','Clue Scrolls (beginner)',
            'Clue Scrolls (easy)','Clue Scrolls (medium)','Clue Scrolls (hard)',
            'Clue Scrolls (elite)','Clue Scrolls (master)','LMS - Rank','Soul Wars Zeal',
            'Abyssal Sire','Alchemical Hydra','Barrows Chests','Bryophyta','Callisto',
            'Cerberus','Chambers of Xeric','Chambers of Xeric: Challenge Mode',
            'Chaos Elemental','Chaos Fanatic','Commander Zilyana','Corporeal Beast',
            'Crazy Archaeologist','Dagannoth Prime','Dagannoth Rex','Dagannoth Supreme',
            'Deranged Archaeologist','General Graardor','Giant Mole','Grotesque Guardians',
            'Hespori','Kalphite Queen','King Black Dragon','Kraken',"Kree'Arra",
            "K'ril Tsutsaroth",'Mimic','Nightmare','Obor','Sarachnis','Scorpia','Skotizo',
            'The Gauntlet','The Corrupted Gauntlet','Theatre of Blood','Thermonuclear Smoke Devil',
            'TzTok-Jad','TzKal-Zuk','Venenatis',"Vet'ion",'Vorkath','Wintertodt','Zalcano','Zulrah']

# Rank Line Config Dict
line_dict = {
        'bronze'  : { 'base' : 3.5 , 'offset' : 10    , 'color' : 'saddlebrown'} ,
        'iron'    : { 'base' : 4   , 'offset' : 75    , 'color' : 'dimgray'} ,
        'steel'   : { 'base' : 5   , 'offset' : 250   , 'color' : 'silver'} ,
        'mirthil' : { 'base' : 6   , 'offset' : 750   , 'color' : 'blue'} ,
        'adamant' : { 'base' : 12  , 'offset' : 1500  , 'color' : 'green'} ,
        'rune'    : { 'base' : 40  , 'offset' : 2500  , 'color' : 'cyan'} ,
        'dragon'  : { 'base' : 100 , 'offset' : 3800  , 'color' : 'red'} ,
        }

# HC EHB Rates
ehb_dict = {
        'Soul Wars Zeal'                    : 250,
        'Abyssal Sire'                      : 25,
        'Alchemical Hydra'                  : 20,
        'Barrows Chests'                    : 18,
        'Bryophyta'                         : 4,
        'Callisto'                          : 20,
        'Cerberus'                          : 45,
        'Chambers of Xeric'                 : 2.5,
        'Chambers of Xeric: Challenge Mode' : 1.5,
        'Chaos Elemental'                   : 30,
        'Chaos Fanatic'                     : 30,
        'Commander Zilyana'                 : 20,
        'Corporeal Beast'                   : 6,
        'Crazy Archaeologist'               : 40,
        'Dagannoth Prime'                   : 80,
        'Dagannoth Rex'                     : 80,
        'Dagannoth Supreme'                 : 80,
        'Deranged Archaeologist'            : 50,
        'General Graardor'                  : 15,
        'Giant Mole'                        : 50,
        'Grotesque Guardians'               : 25,
        'Kalphite Queen'                    : 20,
        'King Black Dragon'                 : 60,
        'Kraken'                            : 60,
        "Kree'Arra"                         : 18,
        "K'ril Tsutsaroth"                  : 18,
        'Nightmare'                         : 10,
        'Obor'                              : 4,         
        'Sarachnis'                         : 40,
        'Scorpia'                           : 25,
        'Skotizo'                           : 1,
        'The Gauntlet'                      : 8,
        'The Corrupted Gauntlet'            : 6,
        'Theatre of Blood'                  : 2.5,
        'Thermonuclear Smoke Devil'         : 70,
        'TzTok-Jad'                         : 2,
        'TzKal-Zuk'                         : 0.8,
        'Venenatis'                         : 30,
        "Vet'ion"                           : 25,
        'Vorkath'                           : 25,
        'Zalcano'                           : 18,
        'Zulrah'                            : 25,
        }

danger_dict = {
        'Soul Wars Zeal'                    : 1,
        'Abyssal Sire'                      : 2,
        'Alchemical Hydra'                  : 2,
        'Barrows Chests'                    : 1,
        'Bryophyta'                         : 1,
        'Callisto'                          : 3,
        'Cerberus'                          : 2,
        'Chambers of Xeric'                 : 1,
        'Chambers of Xeric: Challenge Mode' : 1,
        'Chaos Elemental'                   : 3,
        'Chaos Fanatic'                     : 3,
        'Commander Zilyana'                 : 2,
        'Corporeal Beast'                   : 2,
        'Crazy Archaeologist'               : 2,
        'Dagannoth Prime'                   : 1.5,
        'Dagannoth Rex'                     : 1.5,
        'Dagannoth Supreme'                 : 1.5,
        'Deranged Archaeologist'            : 1.5,
        'General Graardor'                  : 2,
        'Giant Mole'                        : 1,
        'Grotesque Guardians'               : 1.5,
        'Kalphite Queen'                    : 1.5,
        'King Black Dragon'                 : 1.5,
        'Kraken'                            : 1,
        "Kree'Arra"                         : 2,
        "K'ril Tsutsaroth"                  : 2,
        'Nightmare'                         : 2,
        'Obor'                              : 1,         
        'Sarachnis'                         : 1,
        'Scorpia'                           : 3,
        'Skotizo'                           : 1,
        'The Gauntlet'                      : 2,
        'The Corrupted Gauntlet'            : 3,
        'Theatre of Blood'                  : 3,
        'Thermonuclear Smoke Devil'         : 1,
        'TzTok-Jad'                         : 1,
        'TzKal-Zuk'                         : 3,
        'Venenatis'                         : 3,
        "Vet'ion"                           : 3,
        'Vorkath'                           : 2,
        'Zalcano'                           : 1,
        'Zulrah'                            : 1,
        }
