# -*- coding: utf-8 -*-
"""
Created on Sat Feb 27 13:01:13 2021

@author: kneub
"""

import numpy as np

# List of skills from html export
skill_list = ['Overall','Attack','Defence','Strength','Hitpoints','Ranged','Prayer','Magic','Cooking',
              'Woodcutting','Fletching','Fishing','Firemaking','Crafting','Smithing',
              'Mining','Herblore','Agility','Thieving','Slayer','Farming','Runecraft',
              'Hunter','Construction']

# List of bosses from html export
pvm_list = ['Bounty Hunter - Hunter','Clue Scrolls (all)','Clue Scrolls (beginner)',
            'Clue Scrolls (easy)','Clue Scrolls (medium)','Clue Scrolls (hard)',
            'Clue Scrolls (elite)','Clue Scrolls (master)','LMS - Rank','Soul Wars Zeal',
            'Abyssal Sire','Alchemical Hydra','Barrows Chests','Bryophyta','Callisto',
            'Cerberus','Chambers of Xeric','Chambers of Xeric: Challenge Mode',
            'Chaos Elemental','Chaos Fanatic','Commander Zilyana','Corporeal Beast',
            'Crazy Archaeologist','Dagannoth Prime','Dagannoth Rex','Dagannoth Supreme',
            'Deranged Archaeologist','General Graardor','Giant Mole','Grotesque Guardians',
            'Hespori','Kalphite Queen','King Black Dragon','Kraken',"Kree'Arra",
            "K'ril Tsutsaroth",'Mimic','Nightmare','Obor','Sarachnis','Scorpia','Skotizo',
            'The Gauntlet','The Corrupted Gauntlet','Theatre of Blood','Thermonuclear Smoke Devil',
            'TzTok-Jad','TzKal-Zuk','Venenatis',"Vet'ion",'Vorkath','Wintertodt','Zalcano','Zulrah',
            'Tempoross']

odd_pvm_list = ['Bounty Hunter - Hunter','Clue Scrolls (all)','Clue Scrolls (beginner)',
            'Clue Scrolls (easy)','Clue Scrolls (medium)','Clue Scrolls (hard)',
            'Clue Scrolls (elite)','Clue Scrolls (master)','LMS - Rank','Soul Wars Zeal']

# Rank Line Config Dict
line_dict = {
        'bronze'  : { 'base' : 3.5 , 'offset' : 10    , 'k' : 1 , 'color' : 'saddlebrown'} ,
        'iron'    : { 'base' : 4   , 'offset' : 75    , 'k' : 2 , 'color' : 'dimgray'} ,
        'steel'   : { 'base' : 5   , 'offset' : 250   , 'k' : 3 , 'color' : 'silver'} ,
        'mithril' : { 'base' : 8   , 'offset' : 750   , 'k' : 4 , 'color' : 'blue'} ,
        'adamant' : { 'base' : 25  , 'offset' : 1500  , 'k' : 5 , 'color' : 'green'} ,
        'rune'    : { 'base' : 80  , 'offset' : 3000  , 'k' : 6 , 'color' : 'cyan'} ,
        'dragon'  : { 'base' : 250 , 'offset' : 4500  , 'k' : 9 , 'color' : 'red'} ,
        }

# HC EHB Rates
ehb_dict = {
        'Soul Wars Zeal'                    : 250,
        'Abyssal Sire'                      : 25,
        'Alchemical Hydra'                  : 20,
        'Barrows Chests'                    : 18,
        'Bryophyta'                         : 4,
        'Callisto'                          : 20,
        'Cerberus'                          : 45,
        'Chambers of Xeric'                 : 2.5,
        'Chambers of Xeric: Challenge Mode' : 1.5,
        'Chaos Elemental'                   : 30,
        'Chaos Fanatic'                     : 30,
        'Commander Zilyana'                 : 20,
        'Corporeal Beast'                   : 6,
        'Crazy Archaeologist'               : 40,
        'Dagannoth Prime'                   : 80,
        'Dagannoth Rex'                     : 80,
        'Dagannoth Supreme'                 : 80,
        'Deranged Archaeologist'            : 50,
        'General Graardor'                  : 15,
        'Giant Mole'                        : 50,
        'Grotesque Guardians'               : 25,
        'Kalphite Queen'                    : 20,
        'King Black Dragon'                 : 60,
        'Kraken'                            : 60,
        "Kree'Arra"                         : 18,
        "K'ril Tsutsaroth"                  : 18,
        'Nightmare'                         : 10,
        'Obor'                              : 4,         
        'Sarachnis'                         : 40,
        'Scorpia'                           : 25,
        'Skotizo'                           : 1,
        'The Gauntlet'                      : 8,
        'The Corrupted Gauntlet'            : 6,
        'Theatre of Blood'                  : 2.5,
        'Thermonuclear Smoke Devil'         : 70,
        'TzTok-Jad'                         : 2,
        'TzKal-Zuk'                         : 0.8,
        'Venenatis'                         : 30,
        "Vet'ion"                           : 25,
        'Vorkath'                           : 25,
        'Zalcano'                           : 18,
        'Zulrah'                            : 25,
        }

danger_dict = {
        'Soul Wars Zeal'                    : 1,
        'Abyssal Sire'                      : 2,
        'Alchemical Hydra'                  : 2,
        'Barrows Chests'                    : 1,
        'Bryophyta'                         : 1,
        'Callisto'                          : 3,
        'Cerberus'                          : 2,
        'Chambers of Xeric'                 : 1,
        'Chambers of Xeric: Challenge Mode' : 1,
        'Chaos Elemental'                   : 3,
        'Chaos Fanatic'                     : 3,
        'Commander Zilyana'                 : 2,
        'Corporeal Beast'                   : 2,
        'Crazy Archaeologist'               : 2,
        'Dagannoth Prime'                   : 1.5,
        'Dagannoth Rex'                     : 1.5,
        'Dagannoth Supreme'                 : 1.5,
        'Deranged Archaeologist'            : 1.5,
        'General Graardor'                  : 2,
        'Giant Mole'                        : 1,
        'Grotesque Guardians'               : 1.5,
        'Kalphite Queen'                    : 1.5,
        'King Black Dragon'                 : 1.5,
        'Kraken'                            : 1,
        "Kree'Arra"                         : 2,
        "K'ril Tsutsaroth"                  : 2,
        'Nightmare'                         : 2,
        'Obor'                              : 1,         
        'Sarachnis'                         : 1,
        'Scorpia'                           : 3,
        'Skotizo'                           : 1,
        'The Gauntlet'                      : 2,
        'The Corrupted Gauntlet'            : 3,
        'Theatre of Blood'                  : 3,
        'Thermonuclear Smoke Devil'         : 1,
        'TzTok-Jad'                         : 1,
        'TzKal-Zuk'                         : 3,
        'Venenatis'                         : 3,
        "Vet'ion"                           : 3,
        'Vorkath'                           : 2,
        'Zalcano'                           : 1,
        'Zulrah'                            : 1,
        }

pvm_short_dict = {
        'Bounty Hunter - Hunter'            : ['bh','bounty','hunter','bounter hunter','shit pvp'],
        'Clue Scrolls (all)'                : ['clues','clue','all clues','clue scrolls','clue scrolls all','all clues','clues all'],
        'Clue Scrolls (beginner)'           : ['beginner','beginners','beginner clues'],
        'Clue Scrolls (easy)'               : ['easy','easies','easy clues','clue scroll easy','easys'],
        'Clue Scrolls (medium)'             : ['medium','mediums','medium clues','medium clue scrolls','meds','med'],
        'Clue Scrolls (hard)'               : ['hard','hards','hard clues','hard clue scrolls'],
        'Clue Scrolls (elite)'              : ['elite','elites','elite clue','elite clues','elite clue scrolls','saebae','saybay'],
        'Clue Scrolls (master)'             : ['master','masters','master clue','master clues','master clue scrolls'],
        'LMS - Rank'                        : ['lms'],
        'Soul Wars Zeal'                    : ['zeal','soul wars'],
        'Abyssal Sire'                      : ['sire','abyssal'],
        'Alchemical Hydra'                  : ['hydra'],
        'Barrows Chests'                    : ['barrows','brothers'],
        'Bryophyta'                         : ['bryo','byrophyta','byro','moss giant boss','moss giant','big moss giant'],
        'Callisto'                          : ['bear','evensawbowmethod','cub'],
        'Cerberus'                          : ['clifford','cerb','dog'],
        'Chambers of Xeric'                 : ['cox','raids','raid','olm','great olm','the great olm'],
        'Chambers of Xeric: Challenge Mode' : ['cm','cm cox','challenge mode','challenge mode raids'],
        'Chaos Elemental'                   : ['chaos ele','ele'],
        'Chaos Fanatic'                     : ['fanatic'],
        'Commander Zilyana'                 : ['zily','sara','zilyana','saradomin'],
        'Corporeal Beast'                   : ['corp','chicken'],
        'Crazy Archaeologist'               : ['arch','crazy arch','crazy'],
        'Dagannoth Prime'                   : ['prime'],
        'Dagannoth Rex'                     : ['rex'],
        'Dagannoth Supreme'                 : ['supreme'],
        'Deranged Archaeologist'            : ['deranged'],
        'General Graardor'                  : ['general','graardor','bandos','mr. grumbles'],
        'Giant Mole'                        : ['mole','molus erectus'],
        'Grotesque Guardians'               : ['gg','gargs','garg boss','dusk','noon','dawn'],
        'Kalphite Queen'                    : ['kq','queen','kalphite'],
        'King Black Dragon'                 : ['kbd','black dragon'],
        'Kraken'                            : ['tentacle'],
        "Kree'Arra"                         : ['arma','armadyl'],
        "K'ril Tsutsaroth"                  : ['zammy','kril','zamorak'],
        'Nightmare'                         : ['nm'],
        'Obor'                              : ['hill giant'],         
        'Sarachnis'                         : ['saracha','hot sauce'],
        'Scorpia'                           : ['scorpion'],
        'Skotizo'                           : ['skot'],
        'The Gauntlet'                      : ['gauntlet','guant','hunnlef'],
        'The Corrupted Gauntlet'            : ['cg','corrupt gauntlet','corrupted gauntlet','corrupt','corrupted','cgaunt'],
        'Theatre of Blood'                  : ['tob','verzik'],
        'Thermonuclear Smoke Devil'         : ['thermy','smoke devil'],
        'TzTok-Jad'                         : ['jad','fight caves','fire cape'],
        'TzKal-Zuk'                         : ['zuk','inferno'],
        'Venenatis'                         : ['vene'],
        "Vet'ion"                           : ['vetion'],
        'Vorkath'                           : ['vork','vorki'],
        'Zalcano'                           : ['zalc'],
        'Zulrah'                            : ['zul','snake','snek'],
        'Wintertodt'                        : ['todt','wt'],
        'Tempoross'                         : ['temp','temporos','tempeross','temperos','fishingboss']
        }

skill_short_dict = {
        'Overall'                           : ['all'],
        'Attack'                            : ['att'],
        'Defence'                           : ['def','defense'],
        'Strength'                          : ['str'],
        'Hitpoints'                         : ['hp'],
        'Ranged'                            : ['range'],
        'Prayer'                            : ['pray'],
        'Magic'                             : ['mage'],
        'Cooking'                           : ['cook'],
        'Woodcutting'                       : ['wc','wood','chop'],
        'Fletching'                         : ['fletch','why'],
        'Fishing'                           : ['fish'],
        'Firemaking'                        : ['fm','fire'],
        'Crafting'                          : ['craft'],
        'Smithing'                          : ['smith'],
        'Mining'                            : ['mine'],
        'Herblore'                          : ['herb'],
        'Agility'                           : ['agi'],
        'Thieving'                          : ['theiving','thief','thieve','theive'],
        'Slayer'                            : ['slay'],
        'Farming'                           : ['farm'],
        'Runecraft'                         : ['runecrafting','rc','rcing'],
        'Hunter'                            : ['hunt'],
        'Construction'                      : ['con','poh']
        }

command_list = {
        '!update'   : 'Adds player to clan database',
        '!remove'   : 'Removes player from clan database',
        '!xp'       : 'Plots xp for a player',
        '!rank'     : 'Plots rank for a player',
        '!points'   : 'Plots boss kills required for points OR points for a player',
        '!top'      : 'Plots top hardcore boss killers in clan database'
        }

pvm_points_base = np.arange(1,50000)/10